name: Question
description: 按领域向走江人提问
title: "Question"
body:
  - type: dropdown
    id: domain
    attributes:
      label: 所属领域
      options:
        - VMP
        - 改机
        - 风控
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 问题正文
      placeholder: 你的问题...
    validations:
      required: true
