name: Question
description: Ask a question by domain
body:
  - type: dropdown
    id: domain
    attributes:
      label: Domain
      options:
        - VMP
        - Machine
        - Risk
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: Question
    validations:
      required: true
